name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Run unit test
        run: cargo test
      - name: Run linting
        run: cargo clippy --all-targets --all-features -- -D warnings
